AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  APIName:
    Type: String
Resources:
 ApiGateway:
  Type: AWS::ApiGateway::RestApi
  Properties:
    BodyS3Location: NAPI.json
    Name: !Ref APIName

      
       
