AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
Description: 'Creating IAM User and attaching a policy to the user'
Parameters:
  Username:
    Type: String
    MinLength: '1'
    MaxLength: '64'
  Policyname:
    Type : String
Resources:   
  CFNUser:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: 
         Fn::Join: [ "1", [A,!Ref Username,9 ]]
        PasswordResetRequired: Yes
      UserName: !Ref Username
      ManagedPolicyArns: 
            - Fn::ImportValue:
                  !Sub "${Policyname}" 
  CFNKeys:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref 'CFNUser'

