version: 0.1

phases:
  install:
    commands:
      - echo "nothing to do in install"
  pre_build:
    commands:
      - echo "Installing dependencies - `pwd`"
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - aws cloudformation package --template-file /MasterStack.yaml --s3-bucket mybucketfortempate --output-template-file /PackagedTemplate/packaged-template.yaml
  post_build:
    commands:
      - echo "build completed on `date`"

artifacts:
  files:
    - packaged-template.yaml
  discard-paths: yes

