AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Master Template
Resources:
  IAM:
    Properties:
      TemplateURL: IAM/IAM.yaml
    Type: AWS::CloudFormation::Stack
  DynamoDB:
    Properties:
      TemplateURL: DynamoDB/DynamoDB.yaml
    Type: AWS::CloudFormation::Stack
  
    
 
