AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
Description: 'AWS CloudFormation Template DynamoDB secondary Index'
Parameters:
  TableName:
    Type: String
  KeyAttributeName:
    Description: Primary Partition Key Name
    Type: String
    AllowedPattern: '[a-zA-Z0-9]*'
    MinLength: '1'
    MaxLength: '2048'
    ConstraintDescription: must contain only alphanumberic characters
  GSIKeyAttributeName:
    Description: GlobalSecondaryIndexes Key Name
    Type: String
    AllowedPattern: '[a-zA-Z0-9]*'
    MinLength: '1'
    MaxLength: '2048'
    ConstraintDescription: must contain only alphanumberic characters
  KeyAttributeType:
    Description: HashType PrimaryKey Type
    Type: String
    Default: S
    AllowedPattern: '[S|N|B]'
    MinLength: '1'
    MaxLength: '1'
  GSIKeyAttributeType:
    Description: HashType PrimaryKey Type
    Type: String
    Default: S
    AllowedPattern: '[S|N|B]'
    MinLength: '1'
    MaxLength: '1'
  KeyType:
    Type: String
    Default: HASH
    AllowedValues: 
     - HASH
     - RANGE
  GSIKeyType:
    Type: String
    Default: HASH
    AllowedValues: 
     - HASH
     - RANGE
  ProjectionType:
    Type: String
    Default: ALL
    AllowedValues:
      - KEYS_ONLY
      - ALL
  ReadCapacityUnits:
    Description: Provisioned read throughput
    Type: Number
    Default: '5'
    MinValue: '5'
    MaxValue: '10000'
    ConstraintDescription: must be between 5 and 10000
  WriteCapacityUnits:
    Description: Provisioned write throughput
    Type: Number
    Default: '5'
    MinValue: '5'
    MaxValue: '10000'
    ConstraintDescription: must be between 5 and 10000
Resources:
  TableGSI:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
      - AttributeName: !Ref 'KeyAttributeName'
        AttributeType: !Ref 'KeyAttributeType'
      - AttributeName: !Ref 'GSIKeyAttributeName'
        AttributeType: !Ref 'GSIKeyAttributeType'
      KeySchema:
      - AttributeName: !Ref 'KeyAttributeName'
        KeyType: !Ref 'KeyType'
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref 'ReadCapacityUnits'
        WriteCapacityUnits: !Ref 'WriteCapacityUnits'
      GlobalSecondaryIndexes:
      - IndexName: !Ref 'GSIKeyAttributeName'
        KeySchema:
         - AttributeName: !Ref 'GSIKeyAttributeName'
           KeyType: !Ref 'GSIKeyType'
        Projection:
          ProjectionType: !Ref ProjectionType
        ProvisionedThroughput:
          ReadCapacityUnits: !Ref 'ReadCapacityUnits'
          WriteCapacityUnits: !Ref 'WriteCapacityUnits'


