AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation IAM Master Template
Resources:
  Lambda:
    Type: AWS::CloudFormation::Stack 
    Properties:
      TemplateURL: ../env/Functions.yaml
    

        
      
       
