AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
Description: 'Create IAM users'
Resources:
  CreateUserStack01:
    Type : "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: ../Core/Users/UserPolicy.yaml
      Parameters: 
       Username: User1
       Policyname: Policy1