Resources:
  UserPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: Policy1
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Action: '*'
          Resource: '*'  
Outputs:
  UserPolicynew:
   Value: !Ref UserPolicy
   Export:
     Name: Policy1
