AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
Description: 'AWS CloudFormation Sample template showing how to create IAM users'
Resources:
  FunctionRole:
    Type : "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: RolesPolicy.yaml
      Parameters: 
        services: "lambda.amazonaws.com,apigateway.amazonaws.com,events.amazonaws.com"
        Rolename: NAPI-DynamoDB-Development
        Policyname: NAPI-Development-DynamoDB
  
 
