Parameters:
  Policyname:
    Type: String
Resources:
  DynamoDBRead:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Ref Policyname
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: ReadOnlyAccessToDynamoDB
          Effect: Allow
          Action:
          - dynamodb:BatchGetItem
          - dynamodb:DescribeTable
          - dynamodb:GetItem
          - dynamodb:ListTables
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:DescribeReservedCapacity
          - dynamodb:DescribeReservedCapacityOfferings
          - dynamodb:ListTagsOfResource
          - dynamodb:DescribeTimeToLive
          - dynamodb:DescribeLimits
          Resource: "*"
        - Sid: ReadOnlyAccessToCloudWatch
          Effect: Allow
          Action:
          - cloudwatch:DescribeAlarmHistory
          - cloudwatch:DescribeAlarms
          - cloudwatch:DescribeAlarmsForMetric
          - cloudwatch:GetMetricStatistics
          - cloudwatch:ListMetrics
          Resource: "*"
Outputs:
  DynamoDBReadOutput:
   Value: !Ref DynamoDBRead
   Export:
     Name: !Sub "${Policyname}" 
