AWSTemplateFormatVersion: '2010-09-09'
Metadata: 
  License: Apache-2.0
Description: 'Creating IAM User'
Parameters:
  Username:
    Type: String
    Description: New account User
    MinLength: '1'
    MaxLength: '64'
Resources:   
  User:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: 
         Fn::Join: [ "1", [A,!Ref Username,9 ]]
        PasswordResetRequired: Yes
      UserName: !Ref Username
  Keys:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref 'User'

