Parameters:
  Groupname:
    Type: String 
  Username:
    Type: String
Resources:
  addUserToGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref Groupname
      Users:
        - !Ref Username
    DependsOn: mygroup
    
    

    
